apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    name: db-service
    app: voting-app-demo
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: db-deploy-pod